import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:cloud_functions/cloud_functions.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

// `firebase_options.dart` is generated by `flutterfire configure`. It is
// gitignored; each developer runs the CLI locally to generate it.
// import 'package:supporters_bus_app/firebase_options.dart';

const _useEmulator = bool.fromEnvironment('USE_FIREBASE_EMULATOR');
const _emulatorHost = String.fromEnvironment(
  'EMULATOR_HOST',
  defaultValue: 'localhost',
);

Future<void> initializeFirebase() async {
  await Firebase.initializeApp(
    // options: DefaultFirebaseOptions.currentPlatform,
  );

  if (_useEmulator && !kReleaseMode) {
    FirebaseFirestore.instance.useFirestoreEmulator(_emulatorHost, 8080);
    await FirebaseAuth.instance.useAuthEmulator(_emulatorHost, 9099);
    FirebaseFunctions.instance.useFunctionsEmulator(_emulatorHost, 5001);
  }
}
